version: "3.9"

services:
  spark:
    image: marcelmittelstaedt/spark_base:latest
    container_name: hadoop
    ports:
      - 8088:8088 
      - 9870:9870 
      - 9864:9864 
      - 10000:10000
      - 8032:8032 
      - 8030:8030 
      - 8031:8031 
      - 9000:9000 
      - 8888:8888
      - 4040:4040

  airflow:
    build:
      context: ./airflow/
      dockerfile: Dockerfile
    container_name: airflow
    volumes:
      - ./airflow/src:/home/airflow/airflow/dags/
    ports:
      - 8080:8080

volumes:
  data:
    driver: local